services:
  - type: web
    name: dupont-economics
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_VERSION
        value: 18
